[package]
name = "deflate_parser"
version = "0.1.0"
authors = ["mephi42 <mephi42@gmail.com>"]
edition = "2021"

[dependencies]
clap = "3.2.25"
num = "0.4.0"
serde = "1.0.166"
serde_derive = "1.0.166"
serde_json = "1.0.100"
sha2 = "0.10.7"

[profile.release]
debug = true
