[package]
name = "deflate_parser"
version = "0.1.0"
authors = ["mephi42 <mephi42@gmail.com>"]

[dependencies]
clap = "2.33.3"
num = "0.4.0"
serde = "1.0.124"
serde_derive = "1.0.124"
serde_json = "1.0.64"
sha2 = "0.9.3"

[dev-dependencies]
tempfile = "3.2.0"

[profile.release]
debug = true
