[package]
name = "deflate_parser"
version = "0.1.0"
authors = ["mephi42 <mephi42@gmail.com>"]

[dependencies]
clap = "3.1.6"
num = "0.4.0"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
sha2 = "0.10.2"

[dev-dependencies]
tempfile = "3.3.0"

[profile.release]
debug = true
