[package]
name = "deflate_parser"
version = "0.1.0"
authors = ["mephi42 <mephi42@gmail.com>"]

[dependencies]
clap = "2.32.0"
num = "0.2.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
sha2 = "0.8.0"

[dev-dependencies]
tempfile = "3.0.5"

[profile.release]
debug = true
