#!/bin/sh
set -e -u -x
cd "$(dirname "$0")"
cargo fmt
# https://github.com/rust-lang/rust-clippy#travis-ci
cargo clippy --all-targets --all-features -- -D warnings
cargo build
cargo test
cargo build --release
